dospring:
  application:
    name: warehouse-app
#  profiles:
#    active: cloud
  #  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.18.0.2:5432/test_app
    username: postgres_admin
    password: postgres_admin
    hikari:
      schema: public
  liquibase:
    user: postgres_admin
    password: postgres_admin
    url: jdbc:postgresql://172.18.0.2:5432/test_app
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'