#db.driver=org.h2.Driver
#db.url=jdbc:h2:~/test
#db.username=sa
#spring.main.allow-bean-definition-overriding=true
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:config/liquibase/master.xml
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console