
spring:
  #  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.18.0.2:5432/test_app
    username: postgres_admin
    password: postgres_admin
    hikari:
      schema: public
  liquibase:
    user: postgres_admin
    password: postgres_admin
    url: jdbc:postgresql://172.18.0.2:5432/test_app
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
#      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#    properties:
#      hibernate:
#        use_sql_comments: true
#        format_sql: true