POST http://localhost:8080/view/animal/create
Accept: application/json
Content-Type: application/json

{
  "name": "Liluiui",
  "age": 1,
  "sizeAnimal": "MEDIUM"
}

###
POST http://localhost:8080/json/animal/create
Accept: application/json
Content-Type: application/json

{
  "name": "Liluiui",
  "age": 1,
  "sizeAnimal": "MEDIUM"
}