POST http://localhost:8080/view/animal/create
Accept: application/json
Content-Type: application/json

{
  "name": "Liluiui",
  "age": 1,
  "sizeAnimal": "MEDIUM"
}

###
POST http://localhost:8080/json/animal/create
Accept: application/json
Content-Type: application/json

{
  "name": "Liluiui",
  "age": 1,
  "sizeAnimal": "MEDIUM"
}

###
GET http://localhost:8080/json/animal?id=a02c8b6a-03a2-41b7-8b86-a87e19f81fea
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/json/animal/list
Accept: application/json
Content-Type: application/json
